spring.application.name=backend
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/jobquestdb
spring.data.mongodb.database=jobquestdb

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
